/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Barcode_readerIndexRouteImport } from './routes/barcode_reader/index'
import { Route as Barcode_writerIndexRouteImport } from './routes/barcode_writer/index'
import { Route as Csv_swapIndexRouteImport } from './routes/csv_swap/index'
import { Route as Csv_to_tableIndexRouteImport } from './routes/csv_to_table/index'
import { Route as HtmlcheckIndexRouteImport } from './routes/htmlcheck/index'
import { Route as OcrIndexRouteImport } from './routes/ocr/index'
import { Route as Password_generatorIndexRouteImport } from './routes/password_generator/index'
import { Route as TranslateIndexRouteImport } from './routes/translate/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Barcode_readerIndexRoute = Barcode_readerIndexRouteImport.update({
  id: '/barcode_reader/',
  path: '/barcode_reader/',
  getParentRoute: () => rootRouteImport,
} as any)
const Barcode_writerIndexRoute = Barcode_writerIndexRouteImport.update({
  id: '/barcode_writer/',
  path: '/barcode_writer/',
  getParentRoute: () => rootRouteImport,
} as any)
const Csv_swapIndexRoute = Csv_swapIndexRouteImport.update({
  id: '/csv_swap/',
  path: '/csv_swap/',
  getParentRoute: () => rootRouteImport,
} as any)
const Csv_to_tableIndexRoute = Csv_to_tableIndexRouteImport.update({
  id: '/csv_to_table/',
  path: '/csv_to_table/',
  getParentRoute: () => rootRouteImport,
} as any)
const HtmlcheckIndexRoute = HtmlcheckIndexRouteImport.update({
  id: '/htmlcheck/',
  path: '/htmlcheck/',
  getParentRoute: () => rootRouteImport,
} as any)
const OcrIndexRoute = OcrIndexRouteImport.update({
  id: '/ocr/',
  path: '/ocr/',
  getParentRoute: () => rootRouteImport,
} as any)
const Password_generatorIndexRoute = Password_generatorIndexRouteImport.update({
  id: '/password_generator/',
  path: '/password_generator/',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateIndexRoute = TranslateIndexRouteImport.update({
  id: '/translate/',
  path: '/translate/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/barcode_reader/': typeof Barcode_readerIndexRoute
  '/barcode_writer/': typeof Barcode_writerIndexRoute
  '/csv_swap/': typeof Csv_swapIndexRoute
  '/csv_to_table/': typeof Csv_to_tableIndexRoute
  '/htmlcheck/': typeof HtmlcheckIndexRoute
  '/ocr/': typeof OcrIndexRoute
  '/password_generator/': typeof Password_generatorIndexRoute
  '/translate/': typeof TranslateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/barcode_reader': typeof Barcode_readerIndexRoute
  '/barcode_writer': typeof Barcode_writerIndexRoute
  '/csv_swap': typeof Csv_swapIndexRoute
  '/csv_to_table': typeof Csv_to_tableIndexRoute
  '/htmlcheck': typeof HtmlcheckIndexRoute
  '/ocr': typeof OcrIndexRoute
  '/password_generator': typeof Password_generatorIndexRoute
  '/translate': typeof TranslateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/barcode_reader/': typeof Barcode_readerIndexRoute
  '/barcode_writer/': typeof Barcode_writerIndexRoute
  '/csv_swap/': typeof Csv_swapIndexRoute
  '/csv_to_table/': typeof Csv_to_tableIndexRoute
  '/htmlcheck/': typeof HtmlcheckIndexRoute
  '/ocr/': typeof OcrIndexRoute
  '/password_generator/': typeof Password_generatorIndexRoute
  '/translate/': typeof TranslateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/barcode_reader/'
    | '/barcode_writer/'
    | '/csv_swap/'
    | '/csv_to_table/'
    | '/htmlcheck/'
    | '/ocr/'
    | '/password_generator/'
    | '/translate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/barcode_reader'
    | '/barcode_writer'
    | '/csv_swap'
    | '/csv_to_table'
    | '/htmlcheck'
    | '/ocr'
    | '/password_generator'
    | '/translate'
  id:
    | '__root__'
    | '/'
    | '/barcode_reader/'
    | '/barcode_writer/'
    | '/csv_swap/'
    | '/csv_to_table/'
    | '/htmlcheck/'
    | '/ocr/'
    | '/password_generator/'
    | '/translate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Barcode_readerIndexRoute: typeof Barcode_readerIndexRoute
  Barcode_writerIndexRoute: typeof Barcode_writerIndexRoute
  Csv_swapIndexRoute: typeof Csv_swapIndexRoute
  Csv_to_tableIndexRoute: typeof Csv_to_tableIndexRoute
  HtmlcheckIndexRoute: typeof HtmlcheckIndexRoute
  OcrIndexRoute: typeof OcrIndexRoute
  Password_generatorIndexRoute: typeof Password_generatorIndexRoute
  TranslateIndexRoute: typeof TranslateIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barcode_reader/': {
      id: '/barcode_reader/'
      path: '/barcode_reader'
      fullPath: '/barcode_reader/'
      preLoaderRoute: typeof Barcode_readerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barcode_writer/': {
      id: '/barcode_writer/'
      path: '/barcode_writer'
      fullPath: '/barcode_writer/'
      preLoaderRoute: typeof Barcode_writerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv_swap/': {
      id: '/csv_swap/'
      path: '/csv_swap'
      fullPath: '/csv_swap/'
      preLoaderRoute: typeof Csv_swapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv_to_table/': {
      id: '/csv_to_table/'
      path: '/csv_to_table'
      fullPath: '/csv_to_table/'
      preLoaderRoute: typeof Csv_to_tableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/htmlcheck/': {
      id: '/htmlcheck/'
      path: '/htmlcheck'
      fullPath: '/htmlcheck/'
      preLoaderRoute: typeof HtmlcheckIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ocr/': {
      id: '/ocr/'
      path: '/ocr'
      fullPath: '/ocr/'
      preLoaderRoute: typeof OcrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password_generator/': {
      id: '/password_generator/'
      path: '/password_generator'
      fullPath: '/password_generator/'
      preLoaderRoute: typeof Password_generatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate/': {
      id: '/translate/'
      path: '/translate'
      fullPath: '/translate/'
      preLoaderRoute: typeof TranslateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Barcode_readerIndexRoute: Barcode_readerIndexRoute,
  Barcode_writerIndexRoute: Barcode_writerIndexRoute,
  Csv_swapIndexRoute: Csv_swapIndexRoute,
  Csv_to_tableIndexRoute: Csv_to_tableIndexRoute,
  HtmlcheckIndexRoute: HtmlcheckIndexRoute,
  OcrIndexRoute: OcrIndexRoute,
  Password_generatorIndexRoute: Password_generatorIndexRoute,
  TranslateIndexRoute: TranslateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
