name: Cypress CI

on:
  push:
    branches:
      - main
    paths:
      - "src/*"
      - "cypress/*"
      - "cypress.config.ts"

  pull_request:

  workflow_dispatch:

jobs:
  cypress:
    permissions:
      contents: read

    name: Cypress Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Run install
        run: yarn install --frozen-lockfile

      - name: Run local server
        run: yarn test:server

      - name: Run Cypress
        run: yarn test:run
